FROM node:13.12.0-alpine as dev

WORKDIR /usr/src/app/frontend
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci --silent
COPY ./frontend/ ./
RUN npm run build



FROM nginx:1.19.0-alpine

COPY --from=dev /usr/src/app/frontend/build /usr/share/nginx/html

COPY ./default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
